version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  node-app:
    build: .
    image: node-app
    env_file: .env
    ports:
      - '7890:7890'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app

volumes:
  dbdata6:
