version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata7:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shayrad
      - MONGO_INITDB_ROOT_PASSWORD=paklean1392
      - MONGO_INITDB_DATABASE=shayrad_police

  node-app:
    build: .
    image: node-app
    env_file: .env
    ports:
      - '7890:7890'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  dbdata7:
